### ISSUE TITLE
Runtime error when no arguments is passed to acorn login 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1042]
acorn version v0.4.1-112-gb7531fe+b7531fe7

```
 % acorn login 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/acorn-io/acorn/pkg/cli.(*CredentialLogin).Run(0xc00017bec0, 0xc000138600, {0x530ad30, 0x0, 0x0?})
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/credential_login.go:59 +0xacf
github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0xc000138600?, {0x530ad30, 0x0, 0x0})
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:357 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc000138600, {0x530ad30, 0x0, 0x0})
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000034900)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/acorn-io/acorn/pkg/cli.RunAndHandleError({0x3ca7738?, 0xc000760f80?}, 0x3cf449d?)
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/errors.go:19 +0x58
main.main()
	/home/ubuntu/actions-runner/_work/acorn/acorn/main.go:18 +0xf4
```

**Comment by sangee2004** [comment]
The same runtime error is also seen when no arguments is passed to acorn credential login

```
bash-5.2$ acorn credential login 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/acorn-io/acorn/pkg/cli.(*CredentialLogin).Run(0xc0004ee9c0, 0xc000306600, {0x530ad30, 0x0, 0x0?})
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/credential_login.go:59 +0xacf
github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0xc000306600?, {0x530ad30, 0x0, 0x0})
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:357 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc000306600, {0x530ad30, 0x0, 0x0})
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000092600)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/acorn-io/acorn/pkg/cli.RunAndHandleError({0x3ca7738?, 0xc00061a740?}, 0x3cf449d?)
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/cli/errors.go:19 +0x58
main.main()
	/home/ubuntu/actions-runner/_work/acorn/acorn/main.go:18 +0xf4
```

**Comment by sangee2004** [comment]
Tested with acorn version v0.5.0-rc2-2-g6cee142+6cee1422.

This issue is not seen anymore and user is provided with help text. The same is true for acorn credential login as well.


```
 % acorn login
Add registry credentials

Usage:
  acorn login [flags] [SERVER_ADDRESS]

Examples:

acorn login ghcr.io

Flags:
  -h, --help              help for login
  -l, --local-storage     Store credential on local client for push, pull, and build (not run)
  -p, --password string   Password
      --password-stdin    Take the password from stdin
      --skip-checks       Bypass login validation checks
  -u, --username string   Username

Global Flags:
  -A, --all-projects        Use all known projects
      --context string      Context to use in the resolved kubeconfig file
      --debug               Enable debug logging
      --debug-level int     Debug log level (valid 0-9) (default 7)
      --kubeconfig string   Explicitly use kubeconfig file, overriding current project
      --namespace string    Namespace to work in resolved connection (default "acorn")
  -j, --project string      Project to work in
```

**Comment by juicycleff** [comment]
Having this issue now

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x120 pc=0x101f82fa8]

goroutine 1 [running]:
github.com/acorn-io/acorn/pkg/credentials.(*Store).Add(0x14000c8fb58, {0x10322e338, 0x140003e6780}, {{0x16f65700c, 0x20}, {0x14000051790, 0x9}, {0x140002b4d70, 0x47}, 0x0}, ...)
        /Users/darren/actions-runner/_work/acorn/acorn/pkg/credentials/store.go:101 +0x308
github.com/acorn-io/acorn/pkg/cli.(*CredentialLogin).Run(0x14000540740, 0x14000016f00, {0x140002b8150, 0x1, 0x0?})
        /Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/credential_login.go:122 +0x5d4
github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0x14000016f00?, {0x140002b8150, 0x1, 0x1})
        /Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:395 +0x16c
github.com/spf13/cobra.(*Command).execute(0x14000016f00, {0x140002b8120, 0x1, 0x1})
        /Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400021ec00)
        /Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/acorn-io/acorn/pkg/cli.RunAndHandleError({0x10322e338?, 0x140003e6780?}, 0x102a91b7d?)
        /Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/errors.go:16 +0x6c
main.main()
        /Users/darren/actions-runner/_work/acorn/acorn/main.go:18 +0xe0
➜  gateway git:(main) ✗ acorn -v                                                                                                                            git:(main|●8✚2…2 
acorn version v0.6.0+c6ffc99d
```

**Comment by juicycleff** [comment]
It should be reopened

**Comment by sangee2004** [comment]
@juicycleff I am not able to reproduce the issue with  `v0.6.0+c6ffc99d`. Could you please let me know the exact use case you are testing ?

```
% ./acorn credential login
Add registry credentials

Usage:
  acorn credential login [flags] [SERVER_ADDRESS]

Aliases:
  login, add

Examples:

acorn login ghcr.io

Flags:
  -h, --help              help for login
  -l, --local-storage     Store credential on local client for push, pull, and build (not run)
  -p, --password string   Password
      --password-stdin    Take the password from stdin
      --skip-checks       Bypass login validation checks
  -u, --username string   Username

Global Flags:
  -A, --all-projects        Use all known projects
      --debug               Enable debug logging
      --debug-level int     Debug log level (valid 0-9) (default 7)
      --kubeconfig string   Explicitly use kubeconfig file, overriding current project
  -o, --output string       Output format (json, yaml, {{gotemplate}})
  -j, --project string      Project to work in
  -q, --quiet               Output only names


 % ./acorn login           
Add registry credentials

Usage:
  acorn login [flags] [SERVER_ADDRESS]

Examples:

acorn login ghcr.io

Flags:
  -h, --help              help for login
  -l, --local-storage     Store credential on local client for push, pull, and build (not run)
  -p, --password string   Password
      --password-stdin    Take the password from stdin
      --skip-checks       Bypass login validation checks
  -u, --username string   Username

Global Flags:
  -A, --all-projects        Use all known projects
      --debug               Enable debug logging
      --debug-level int     Debug log level (valid 0-9) (default 7)
      --kubeconfig string   Explicitly use kubeconfig file, overriding current project
  -j, --project string      Project to work in

 % ./acorn --version
acorn version v0.6.0+c6ffc99d

**Comment by juicycleff** [comment]
> @juicycleff I am not able to reproduce the issue with  `v0.6.0+c6ffc99d`. Could you please let me know the exact use case you are testing ?
> 
> 
> 
> ```
> 
> % ./acorn credential login
> 
> Add registry credentials
> 
> 
> 
> Usage:
> 
>   acorn credential login [flags] [SERVER_ADDRESS]
> 
> 
> 
> Aliases:
> 
>   login, add
> 
> 
> 
> Examples:
> 
> 
> 
> acorn login ghcr.io
> 
> 
> 
> Flags:
> 
>   -h, --help              help for login
> 
>   -l, --local-storage     Store credential on local client for push, pull, and build (not run)
> 
>   -p, --password string   Password
> 
>       --password-stdin    Take the password from stdin
> 
>       --skip-checks       Bypass login validation checks
> 
>   -u, --username string   Username
> 
> 
> 
> Global Flags:
> 
>   -A, --all-projects        Use all known projects
> 
>       --debug               Enable debug logging
> 
>       --debug-level int     Debug log level (valid 0-9) (default 7)
> 
>       --kubeconfig string   Explicitly use kubeconfig file, overriding current project
> 
>   -o, --output string       Output format (json, yaml, {{gotemplate}})
> 
>   -j, --project string      Project to work in
> 
>   -q, --quiet               Output only names
> 
> 
> 
> 
> 
>  % ./acorn login           
> 
> Add registry credentials
> 
> 
> 
> Usage:
> 
>   acorn login [flags] [SERVER_ADDRESS]
> 
> 
> 
> Examples:
> 
> 
> 
> acorn login ghcr.io
> 
> 
> 
> Flags:
> 
>   -h, --help              help for login
> 
>   -l, --local-storage     Store credential on local client for push, pull, and build (not run)
> 
>   -p, --password string   Password
> 
>       --password-stdin    Take the password from stdin
> 
>       --skip-checks       Bypass login validation checks
> 
>   -u, --username string   Username
> 
> 
> 
> Global Flags:
> 
>   -A, --all-projects        Use all known projects
> 
>       --debug               Enable debug logging
> 
>       --debug-level int     Debug log level (valid 0-9) (default 7)
> 
>       --kubeconfig string   Explicitly use kubeconfig file, overriding current project
> 
>   -j, --project string      Project to work in
> 
> 
> 
>  % ./acorn --version
> 
> acorn version v0.6.0+c6ffc99d
> 
> 
> 
> 

So I figured the problem acorn only works with GitHub Packages nothing else. I was trying to set the registry to digital ocean and it kept failing with the above error.

I had to move to GitHub packages from DO container registry because of this. I'd say the error should be be handled gracefully instead of crashing, so I guess that's one bug. Would have loved to create a PR to fix it but on tight deadlines

**Comment by sangee2004** [comment]
@juicycleff Will log an issue to track the behavior you are seeing. Thank you for reporting it.
