### ISSUE TITLE
runtime error  when trying to list projects.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1479]
acorn --version
acorn version v0.6.0-145-g1f6d90fd+1f6d90fd

Steps to reproduce the problem:

Tried to list projects as soon as I logged in to remote server.

```
acorn login -p xxx <remote server>
acorn project use <remote server>/<account>/mytestsandbox

  •  Run "acorn projects xxx" to list available projects
  •  Run "acorn project use xxx/<account>/mytestsandbox" to set default project
  ✔  Login to xxxx as <account> succeeded

 % acorn project
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x32823f9]

goroutine 211 [running]:
github.com/acorn-io/acorn/pkg/project.GetDetails.func1({0xc0005a6de0, 0x28}, {{0xc0005a6de0, 0x28}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...})
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/project/operations.go:205 +0x119
created by github.com/acorn-io/acorn/pkg/project.GetDetails
	/home/ubuntu/actions-runner/_work/acorn/acorn/pkg/project/operations.go:199 +0x88

```

On retry, worked fine.

**Comment by sangee2004** [comment]
I hit a similar problem again.


```
acorn projects
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x3250fb9]

goroutine 182 [running]:
github.com/acorn-io/acorn/pkg/project.GetDetails.func1({0xc0002e7bf0, 0x2b}, {{0xc0002e7bf0, 0x2b}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...})
	/home/runner/actions-runner/_work/acorn/acorn/pkg/project/operations.go:205 +0x119
created by github.com/acorn-io/acorn/pkg/project.GetDetails
	/home/runner/actions-runner/_work/acorn/acorn/pkg/project/operations.go:199 +0x88
sangeethahariharan@Sangeethas-MBP example1 % acorn projects
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x3250fb9]

goroutine 182 [running]:
github.com/acorn-io/acorn/pkg/project.GetDetails.func1({0xc000620ff0, 0x28}, {{0xc000620ff0, 0x28}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...})
	/home/runner/actions-runner/_work/acorn/acorn/pkg/project/operations.go:205 +0x119
created by github.com/acorn-io/acorn/pkg/project.GetDetails
	/home/runner/actions-runner/_work/acorn/acorn/pkg/project/operations.go:199 +0x88
```

**Comment by sangee2004** [comment]
acorn version `v0.6.0-187-gec31b1ac+ec31b1ac`

No runtime errors seen when listing projects.
