### ISSUE TITLE
saying no to acorn run results in nil pointer

### ISSUE THREAD

**Issue by ekristen** [acorn-io/acorn#424]
```
acorn run ghcr.io/acorn-io/library/mariadb:v10.6.8-focal-acorn.1
? Acorn is not installed, do you want to install it now?: No
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d8e416]

goroutine 1 [running]:
github.com/acorn-io/acorn/pkg/deployargs.ToFlagsFromImage({0x39704f8?, 0xc0008de2c0?}, {0x398ded8?, 0xc0005d8d00?}, {0x7ffeefbfefa2, 0x36})
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/deployargs/args.go:39 +0x56
github.com/acorn-io/acorn/pkg/cli.(*Run).Run(0xc0004b8410, 0xc000800280, {0xc0005a42a0?, 0x3, 0x3})
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/run.go:171 +0x63d
github.com/acorn-io/acorn/pkg/cli/builder.bind.func1(0xc000800280?, {0xc0005a42a0, 0x3, 0x3})
	/Users/darren/actions-runner/_work/acorn/acorn/pkg/cli/builder/builder.go:351 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc000800280, {0xc0005a4270, 0x3, 0x3})
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f4500)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/darren/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
	/Users/darren/actions-runner/_work/acorn/acorn/main.go:17 +0x118
```

**Comment by thedadams** [comment]
Looks like this was fixed by https://github.com/acorn-io/acorn/pull/427

**Comment by cjellick** [comment]
Now that's what I call QA.
